file_format: "1"
id: poko
name: POKO (split-wireless)
type: shield
url: https://github.com/ryoo14/poko
requires: [xiao_ble]
features:
  - keys
  - pointer
  - studio
siblings:
  - poko_left
  - poko_right
